from enum import Enum
import json
import os
import pandas as pd

# dataset files
course_pd = pd.read_excel(os.path.join("src", "utils", "Brain-TR-GammaKnife_Clinical_Information.xlsx"), sheet_name="course_level")
lesion_pd = pd.read_excel(os.path.join("src", "utils", "Brain-TR-GammaKnife_Clinical_Information.xlsx"), sheet_name="lesion_level")

# labels incldung background
LABEL_MAP = {"background" : 0, "temporal": 1, "frontal": 2, "occipital": 3, "parietal" : 4, "cerebellar" : 5} #,  "uncategorized" : 6} # 
ID_TO_LABEL = {}
for key,value in LABEL_MAP.items():
    ID_TO_LABEL[value] = key

#  classification types 
class TYPES(Enum):
    GENDER = "gender"
    LOCATION = "location"
    LOCATION_DIRECTION = "location_direction"
    AGE = "age"
    TUMOR = "tumor"
# gender labels
genders = {"labels" : ["Male", "Female"]}
gender_to_id = {gender: i for i, gender in enumerate(["Male", "Female"])}
gender_ids = [gender_to_id[gender] for gender in ["Male", "Female"]]

# location labels
locations = {"labels" :  ["temporal", "frontal", "occipital", "parietal", "cerebellar"]} # "uncategorized"

# locaation directions labels
directions = ['left', 'right']
locations_directions = []
for location in locations['labels']:
    if location != 'uncategorized':
        for direction in directions:
            locations_directions.append(direction + ' ' + location)
    else:
        locations_directions.append(location)
locations_directions = {"labels" : locations_directions}

# combined type lists
types = {TYPES.GENDER : genders, TYPES.LOCATION : locations, TYPES.LOCATION_DIRECTION : locations_directions}

# model layer names for freezing bert or swint encoders
text_layers_names = [
'text.embeddings.word_embeddings.weight',
'text.embeddings.position_embeddings.weight',
'text.embeddings.token_type_embeddings.weight',
'text.embeddings.LayerNorm.gamma',
'text.embeddings.LayerNorm.beta',
'text.encoder.layer.0.attention.self.query.weight',
'text.encoder.layer.0.attention.self.query.bias',
'text.encoder.layer.0.attention.self.key.weight',
'text.encoder.layer.0.attention.self.key.bias',
'text.encoder.layer.0.attention.self.value.weight',
'text.encoder.layer.0.attention.self.value.bias',
'text.encoder.layer.0.attention.output.dense.weight',
'text.encoder.layer.0.attention.output.dense.bias',
'text.encoder.layer.0.attention.output.LayerNorm.gamma',
'text.encoder.layer.0.attention.output.LayerNorm.beta',
'text.encoder.layer.0.intermediate.dense.weight',
'text.encoder.layer.0.intermediate.dense.bias',
'text.encoder.layer.0.output.dense.weight',
'text.encoder.layer.0.output.dense.bias',
'text.encoder.layer.0.output.LayerNorm.gamma',
'text.encoder.layer.0.output.LayerNorm.beta',
'text.encoder.layer.1.attention.self.query.weight',
'text.encoder.layer.1.attention.self.query.bias',
'text.encoder.layer.1.attention.self.key.weight',
'text.encoder.layer.1.attention.self.key.bias',
'text.encoder.layer.1.attention.self.value.weight',
'text.encoder.layer.1.attention.self.value.bias',
'text.encoder.layer.1.attention.output.dense.weight',
'text.encoder.layer.1.attention.output.dense.bias',
'text.encoder.layer.1.attention.output.LayerNorm.gamma',
'text.encoder.layer.1.attention.output.LayerNorm.beta',
'text.encoder.layer.1.intermediate.dense.weight',
'text.encoder.layer.1.intermediate.dense.bias',
'text.encoder.layer.1.output.dense.weight',
'text.encoder.layer.1.output.dense.bias',
'text.encoder.layer.1.output.LayerNorm.gamma',
'text.encoder.layer.1.output.LayerNorm.beta',
'text.encoder.layer.2.attention.self.query.weight',
'text.encoder.layer.2.attention.self.query.bias',
'text.encoder.layer.2.attention.self.key.weight',
'text.encoder.layer.2.attention.self.key.bias',
'text.encoder.layer.2.attention.self.value.weight',
'text.encoder.layer.2.attention.self.value.bias',
'text.encoder.layer.2.attention.output.dense.weight',
'text.encoder.layer.2.attention.output.dense.bias',
'text.encoder.layer.2.attention.output.LayerNorm.gamma',
'text.encoder.layer.2.attention.output.LayerNorm.beta',
'text.encoder.layer.2.intermediate.dense.weight',
'text.encoder.layer.2.intermediate.dense.bias',
'text.encoder.layer.2.output.dense.weight',
'text.encoder.layer.2.output.dense.bias',
'text.encoder.layer.2.output.LayerNorm.gamma',
'text.encoder.layer.2.output.LayerNorm.beta',
'text.encoder.layer.3.attention.self.query.weight',
'text.encoder.layer.3.attention.self.query.bias',
'text.encoder.layer.3.attention.self.key.weight',
'text.encoder.layer.3.attention.self.key.bias',
'text.encoder.layer.3.attention.self.value.weight',
'text.encoder.layer.3.attention.self.value.bias',
'text.encoder.layer.3.attention.output.dense.weight',
'text.encoder.layer.3.attention.output.dense.bias',
'text.encoder.layer.3.attention.output.LayerNorm.gamma',
'text.encoder.layer.3.attention.output.LayerNorm.beta',
'text.encoder.layer.3.intermediate.dense.weight',
'text.encoder.layer.3.intermediate.dense.bias',
'text.encoder.layer.3.output.dense.weight',
'text.encoder.layer.3.output.dense.bias',
'text.encoder.layer.3.output.LayerNorm.gamma',
'text.encoder.layer.3.output.LayerNorm.beta',
'text.encoder.layer.4.attention.self.query.weight',
'text.encoder.layer.4.attention.self.query.bias',
'text.encoder.layer.4.attention.self.key.weight',
'text.encoder.layer.4.attention.self.key.bias',
'text.encoder.layer.4.attention.self.value.weight',
'text.encoder.layer.4.attention.self.value.bias',
'text.encoder.layer.4.attention.output.dense.weight',
'text.encoder.layer.4.attention.output.dense.bias',
'text.encoder.layer.4.attention.output.LayerNorm.gamma',
'text.encoder.layer.4.attention.output.LayerNorm.beta',
'text.encoder.layer.4.intermediate.dense.weight',
'text.encoder.layer.4.intermediate.dense.bias',
'text.encoder.layer.4.output.dense.weight',
'text.encoder.layer.4.output.dense.bias',
'text.encoder.layer.4.output.LayerNorm.gamma',
'text.encoder.layer.4.output.LayerNorm.beta',
'text.encoder.layer.5.attention.self.query.weight',
'text.encoder.layer.5.attention.self.query.bias',
'text.encoder.layer.5.attention.self.key.weight',
'text.encoder.layer.5.attention.self.key.bias',
'text.encoder.layer.5.attention.self.value.weight',
'text.encoder.layer.5.attention.self.value.bias',
'text.encoder.layer.5.attention.output.dense.weight',
'text.encoder.layer.5.attention.output.dense.bias',
'text.encoder.layer.5.attention.output.LayerNorm.gamma',
'text.encoder.layer.5.attention.output.LayerNorm.beta',
'text.encoder.layer.5.intermediate.dense.weight',
'text.encoder.layer.5.intermediate.dense.bias',
'text.encoder.layer.5.output.dense.weight',
'text.encoder.layer.5.output.dense.bias',
'text.encoder.layer.5.output.LayerNorm.gamma',
'text.encoder.layer.5.output.LayerNorm.beta',
'text.encoder.layer.6.attention.self.query.weight',
'text.encoder.layer.6.attention.self.query.bias',
'text.encoder.layer.6.attention.self.key.weight',
'text.encoder.layer.6.attention.self.key.bias',
'text.encoder.layer.6.attention.self.value.weight',
'text.encoder.layer.6.attention.self.value.bias',
'text.encoder.layer.6.attention.output.dense.weight',
'text.encoder.layer.6.attention.output.dense.bias',
'text.encoder.layer.6.attention.output.LayerNorm.gamma',
'text.encoder.layer.6.attention.output.LayerNorm.beta',
'text.encoder.layer.6.intermediate.dense.weight',
'text.encoder.layer.6.intermediate.dense.bias',
'text.encoder.layer.6.output.dense.weight',
'text.encoder.layer.6.output.dense.bias',
'text.encoder.layer.6.output.LayerNorm.gamma',
'text.encoder.layer.6.output.LayerNorm.beta',
'text.encoder.layer.7.attention.self.query.weight',
'text.encoder.layer.7.attention.self.query.bias',
'text.encoder.layer.7.attention.self.key.weight',
'text.encoder.layer.7.attention.self.key.bias',
'text.encoder.layer.7.attention.self.value.weight',
'text.encoder.layer.7.attention.self.value.bias',
'text.encoder.layer.7.attention.output.dense.weight',
'text.encoder.layer.7.attention.output.dense.bias',
'text.encoder.layer.7.attention.output.LayerNorm.gamma',
'text.encoder.layer.7.attention.output.LayerNorm.beta',
'text.encoder.layer.7.intermediate.dense.weight',
'text.encoder.layer.7.intermediate.dense.bias',
'text.encoder.layer.7.output.dense.weight',
'text.encoder.layer.7.output.dense.bias',
'text.encoder.layer.7.output.LayerNorm.gamma',
'text.encoder.layer.7.output.LayerNorm.beta',
'text.encoder.layer.8.attention.self.query.weight',
'text.encoder.layer.8.attention.self.query.bias',
'text.encoder.layer.8.attention.self.key.weight',
'text.encoder.layer.8.attention.self.key.bias',
'text.encoder.layer.8.attention.self.value.weight',
'text.encoder.layer.8.attention.self.value.bias',
'text.encoder.layer.8.attention.output.dense.weight',
'text.encoder.layer.8.attention.output.dense.bias',
'text.encoder.layer.8.attention.output.LayerNorm.gamma',
'text.encoder.layer.8.attention.output.LayerNorm.beta',
'text.encoder.layer.8.intermediate.dense.weight',
'text.encoder.layer.8.intermediate.dense.bias',
'text.encoder.layer.8.output.dense.weight',
'text.encoder.layer.8.output.dense.bias',
'text.encoder.layer.8.output.LayerNorm.gamma',
'text.encoder.layer.8.output.LayerNorm.beta',
'text.encoder.layer.9.attention.self.query.weight',
'text.encoder.layer.9.attention.self.query.bias',
'text.encoder.layer.9.attention.self.key.weight',
'text.encoder.layer.9.attention.self.key.bias',
'text.encoder.layer.9.attention.self.value.weight',
'text.encoder.layer.9.attention.self.value.bias',
'text.encoder.layer.9.attention.output.dense.weight',
'text.encoder.layer.9.attention.output.dense.bias',
'text.encoder.layer.9.attention.output.LayerNorm.gamma',
'text.encoder.layer.9.attention.output.LayerNorm.beta',
'text.encoder.layer.9.intermediate.dense.weight',
'text.encoder.layer.9.intermediate.dense.bias',
'text.encoder.layer.9.output.dense.weight',
'text.encoder.layer.9.output.dense.bias',
'text.encoder.layer.9.output.LayerNorm.gamma',
'text.encoder.layer.9.output.LayerNorm.beta',
'text.encoder.layer.10.attention.self.query.weight',
'text.encoder.layer.10.attention.self.query.bias',
'text.encoder.layer.10.attention.self.key.weight',
'text.encoder.layer.10.attention.self.key.bias',
'text.encoder.layer.10.attention.self.value.weight',
'text.encoder.layer.10.attention.self.value.bias',
'text.encoder.layer.10.attention.output.dense.weight',
'text.encoder.layer.10.attention.output.dense.bias',
'text.encoder.layer.10.attention.output.LayerNorm.gamma',
'text.encoder.layer.10.attention.output.LayerNorm.beta',
'text.encoder.layer.10.intermediate.dense.weight',
'text.encoder.layer.10.intermediate.dense.bias',
'text.encoder.layer.10.output.dense.weight',
'text.encoder.layer.10.output.dense.bias',
'text.encoder.layer.10.output.LayerNorm.gamma',
'text.encoder.layer.10.output.LayerNorm.beta',
'text.encoder.layer.11.attention.self.query.weight',
'text.encoder.layer.11.attention.self.query.bias',
'text.encoder.layer.11.attention.self.key.weight',
'text.encoder.layer.11.attention.self.key.bias',
'text.encoder.layer.11.attention.self.value.weight',
'text.encoder.layer.11.attention.self.value.bias',
'text.encoder.layer.11.attention.output.dense.weight',
'text.encoder.layer.11.attention.output.dense.bias',
'text.encoder.layer.11.attention.output.LayerNorm.gamma',
'text.encoder.layer.11.attention.output.LayerNorm.beta',
'text.encoder.layer.11.intermediate.dense.weight',
'text.encoder.layer.11.intermediate.dense.bias',
'text.encoder.layer.11.output.dense.weight',
'text.encoder.layer.11.output.dense.bias',
'text.encoder.layer.11.output.LayerNorm.gamma',
'text.encoder.layer.11.output.LayerNorm.beta',
'text.pooler.dense.weight',
'text.pooler.dense.bias'
]
vision_layers_names = [
'vision.swinViT.patch_embed.proj.weight',
'vision.swinViT.patch_embed.proj.bias',
'vision.swinViT.layers1.0.blocks.0.norm1.weight',
'vision.swinViT.layers1.0.blocks.0.norm1.bias',
'vision.swinViT.layers1.0.blocks.0.attn.relative_position_bias_table',
'vision.swinViT.layers1.0.blocks.0.attn.qkv.weight',
'vision.swinViT.layers1.0.blocks.0.attn.qkv.bias',
'vision.swinViT.layers1.0.blocks.0.attn.proj.weight',
'vision.swinViT.layers1.0.blocks.0.attn.proj.bias',
'vision.swinViT.layers1.0.blocks.0.norm2.weight',
'vision.swinViT.layers1.0.blocks.0.norm2.bias',
'vision.swinViT.layers1.0.blocks.0.mlp.linear1.weight',
'vision.swinViT.layers1.0.blocks.0.mlp.linear1.bias',
'vision.swinViT.layers1.0.blocks.0.mlp.linear2.weight',
'vision.swinViT.layers1.0.blocks.0.mlp.linear2.bias',
'vision.swinViT.layers1.0.blocks.1.norm1.weight',
'vision.swinViT.layers1.0.blocks.1.norm1.bias',
'vision.swinViT.layers1.0.blocks.1.attn.relative_position_bias_table',
'vision.swinViT.layers1.0.blocks.1.attn.qkv.weight',
'vision.swinViT.layers1.0.blocks.1.attn.qkv.bias',
'vision.swinViT.layers1.0.blocks.1.attn.proj.weight',
'vision.swinViT.layers1.0.blocks.1.attn.proj.bias',
'vision.swinViT.layers1.0.blocks.1.norm2.weight',
'vision.swinViT.layers1.0.blocks.1.norm2.bias',
'vision.swinViT.layers1.0.blocks.1.mlp.linear1.weight',
'vision.swinViT.layers1.0.blocks.1.mlp.linear1.bias',
'vision.swinViT.layers1.0.blocks.1.mlp.linear2.weight',
'vision.swinViT.layers1.0.blocks.1.mlp.linear2.bias',
'vision.swinViT.layers1.0.downsample.reduction.weight',
'vision.swinViT.layers1.0.downsample.norm.weight',
'vision.swinViT.layers1.0.downsample.norm.bias',
'vision.swinViT.layers2.0.blocks.0.norm1.weight',
'vision.swinViT.layers2.0.blocks.0.norm1.bias',
'vision.swinViT.layers2.0.blocks.0.attn.relative_position_bias_table',
'vision.swinViT.layers2.0.blocks.0.attn.qkv.weight',
'vision.swinViT.layers2.0.blocks.0.attn.qkv.bias',
'vision.swinViT.layers2.0.blocks.0.attn.proj.weight',
'vision.swinViT.layers2.0.blocks.0.attn.proj.bias',
'vision.swinViT.layers2.0.blocks.0.norm2.weight',
'vision.swinViT.layers2.0.blocks.0.norm2.bias',
'vision.swinViT.layers2.0.blocks.0.mlp.linear1.weight',
'vision.swinViT.layers2.0.blocks.0.mlp.linear1.bias',
'vision.swinViT.layers2.0.blocks.0.mlp.linear2.weight',
'vision.swinViT.layers2.0.blocks.0.mlp.linear2.bias',
'vision.swinViT.layers2.0.blocks.1.norm1.weight',
'vision.swinViT.layers2.0.blocks.1.norm1.bias',
'vision.swinViT.layers2.0.blocks.1.attn.relative_position_bias_table',
'vision.swinViT.layers2.0.blocks.1.attn.qkv.weight',
'vision.swinViT.layers2.0.blocks.1.attn.qkv.bias',
'vision.swinViT.layers2.0.blocks.1.attn.proj.weight',
'vision.swinViT.layers2.0.blocks.1.attn.proj.bias',
'vision.swinViT.layers2.0.blocks.1.norm2.weight',
'vision.swinViT.layers2.0.blocks.1.norm2.bias',
'vision.swinViT.layers2.0.blocks.1.mlp.linear1.weight',
'vision.swinViT.layers2.0.blocks.1.mlp.linear1.bias',
'vision.swinViT.layers2.0.blocks.1.mlp.linear2.weight',
'vision.swinViT.layers2.0.blocks.1.mlp.linear2.bias',
'vision.swinViT.layers2.0.downsample.reduction.weight',
'vision.swinViT.layers2.0.downsample.norm.weight',
'vision.swinViT.layers2.0.downsample.norm.bias',
'vision.swinViT.layers3.0.blocks.0.norm1.weight',
'vision.swinViT.layers3.0.blocks.0.norm1.bias',
'vision.swinViT.layers3.0.blocks.0.attn.relative_position_bias_table',
'vision.swinViT.layers3.0.blocks.0.attn.qkv.weight',
'vision.swinViT.layers3.0.blocks.0.attn.qkv.bias',
'vision.swinViT.layers3.0.blocks.0.attn.proj.weight',
'vision.swinViT.layers3.0.blocks.0.attn.proj.bias',
'vision.swinViT.layers3.0.blocks.0.norm2.weight',
'vision.swinViT.layers3.0.blocks.0.norm2.bias',
'vision.swinViT.layers3.0.blocks.0.mlp.linear1.weight',
'vision.swinViT.layers3.0.blocks.0.mlp.linear1.bias',
'vision.swinViT.layers3.0.blocks.0.mlp.linear2.weight',
'vision.swinViT.layers3.0.blocks.0.mlp.linear2.bias',
'vision.swinViT.layers3.0.blocks.1.norm1.weight',
'vision.swinViT.layers3.0.blocks.1.norm1.bias',
'vision.swinViT.layers3.0.blocks.1.attn.relative_position_bias_table',
'vision.swinViT.layers3.0.blocks.1.attn.qkv.weight',
'vision.swinViT.layers3.0.blocks.1.attn.qkv.bias',
'vision.swinViT.layers3.0.blocks.1.attn.proj.weight',
'vision.swinViT.layers3.0.blocks.1.attn.proj.bias',
'vision.swinViT.layers3.0.blocks.1.norm2.weight',
'vision.swinViT.layers3.0.blocks.1.norm2.bias',
'vision.swinViT.layers3.0.blocks.1.mlp.linear1.weight',
'vision.swinViT.layers3.0.blocks.1.mlp.linear1.bias',
'vision.swinViT.layers3.0.blocks.1.mlp.linear2.weight',
'vision.swinViT.layers3.0.blocks.1.mlp.linear2.bias',
'vision.swinViT.layers3.0.downsample.reduction.weight',
'vision.swinViT.layers3.0.downsample.norm.weight',
'vision.swinViT.layers3.0.downsample.norm.bias',
'vision.swinViT.layers4.0.blocks.0.norm1.weight',
'vision.swinViT.layers4.0.blocks.0.norm1.bias',
'vision.swinViT.layers4.0.blocks.0.attn.relative_position_bias_table',
'vision.swinViT.layers4.0.blocks.0.attn.qkv.weight',
'vision.swinViT.layers4.0.blocks.0.attn.qkv.bias',
'vision.swinViT.layers4.0.blocks.0.attn.proj.weight',
'vision.swinViT.layers4.0.blocks.0.attn.proj.bias',
'vision.swinViT.layers4.0.blocks.0.norm2.weight',
'vision.swinViT.layers4.0.blocks.0.norm2.bias',
'vision.swinViT.layers4.0.blocks.0.mlp.linear1.weight',
'vision.swinViT.layers4.0.blocks.0.mlp.linear1.bias',
'vision.swinViT.layers4.0.blocks.0.mlp.linear2.weight',
'vision.swinViT.layers4.0.blocks.0.mlp.linear2.bias',
'vision.swinViT.layers4.0.blocks.1.norm1.weight',
'vision.swinViT.layers4.0.blocks.1.norm1.bias',
'vision.swinViT.layers4.0.blocks.1.attn.relative_position_bias_table',
'vision.swinViT.layers4.0.blocks.1.attn.qkv.weight',
'vision.swinViT.layers4.0.blocks.1.attn.qkv.bias',
'vision.swinViT.layers4.0.blocks.1.attn.proj.weight',
'vision.swinViT.layers4.0.blocks.1.attn.proj.bias',
'vision.swinViT.layers4.0.blocks.1.norm2.weight',
'vision.swinViT.layers4.0.blocks.1.norm2.bias',
'vision.swinViT.layers4.0.blocks.1.mlp.linear1.weight',
'vision.swinViT.layers4.0.blocks.1.mlp.linear1.bias',
'vision.swinViT.layers4.0.blocks.1.mlp.linear2.weight',
'vision.swinViT.layers4.0.blocks.1.mlp.linear2.bias',
'vision.swinViT.layers4.0.downsample.reduction.weight',
'vision.swinViT.layers4.0.downsample.norm.weight',
'vision.swinViT.layers4.0.downsample.norm.bias',
'vision.rotation_head.weight',
'vision.rotation_head.bias',
'vision.contrastive_head.weight',
'vision.contrastive_head.bias',
'vision.rec_head.0.weight',
'vision.rec_head.0.bias',
'vision.rec_head.4.weight',
'vision.rec_head.4.bias',
'vision.rec_head.8.weight',
'vision.rec_head.8.bias',
'vision.rec_head.12.weight',
'vision.rec_head.12.bias',
'vision.rec_head.16.weight',
'vision.rec_head.16.bias',
'vision.rec_head.20.weight',
'vision.rec_head.20.bias',
]
